# -*- coding: utf-8 -*-
"""dasku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_5uLLpzDBtQENvZP99hnJy8C0i4Wufl5
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

st.set_page_config(page_title="Dashboard Bike Sharing", layout="wide")

# Judul
st.title("🚴 Dashboard Analisis Bike Sharing")
st.markdown("Gunakan filter di sidebar untuk eksplorasi data lebih interaktif.")

# Sidebar untuk upload dan filter
st.sidebar.header("⚙️ Pengaturan")

uploaded_file = st.sidebar.file_uploader("📂 Upload dataset Bike Sharing (CSV)", type="csv")

if uploaded_file:
    # Baca dataset
    df = pd.read_csv(uploaded_file)
    st.success("✅ Dataset berhasil diupload!")

    # --- Sidebar Filter ---
    musim_map = {1: "Spring", 2: "Summer", 3: "Fall", 4: "Winter"}
    cuaca_map = {1: "Cerah", 2: "Berkabut", 3: "Hujan Ringan", 4: "Hujan Lebat"}
    hari_map = {0: "Weekend", 1: "Weekday"}

    musim_terpilih = st.sidebar.multiselect(
        "Pilih Musim", options=list(musim_map.keys()), format_func=lambda x: musim_map[x]
    )
    cuaca_terpilih = st.sidebar.multiselect(
        "Pilih Kondisi Cuaca", options=list(cuaca_map.keys()), format_func=lambda x: cuaca_map[x]
    )
    hari_terpilih = st.sidebar.multiselect(
        "Pilih Hari (Weekday/Weekend)", options=list(hari_map.keys()), format_func=lambda x: hari_map[x]
    )

    # Terapkan filter
    df_filtered = df.copy()
    if musim_terpilih:
        df_filtered = df_filtered[df_filtered["season"].isin(musim_terpilih)]
    if cuaca_terpilih:
        df_filtered = df_filtered[df_filtered["weathersit"].isin(cuaca_terpilih)]
    if hari_terpilih:
        df_filtered = df_filtered[df_filtered["workingday"].isin(hari_terpilih)]

    # Preview data
    st.subheader("📋 Data Terfilter")
    st.write(df_filtered.head())

    # --- Pertanyaan 1 ---
    st.header("❓ Pertanyaan 1: Pola Penggunaan Sepeda Berdasarkan Musim & Cuaca")

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Rata-rata Penggunaan per Musim")
        if "season" in df_filtered.columns and "cnt" in df_filtered.columns:
            season_usage = df_filtered.groupby("season")["cnt"].mean()
            if not season_usage.empty:
                season_usage.index = season_usage.index.map(musim_map)
                fig, ax = plt.subplots()
                season_usage.plot(kind="bar", ax=ax, color="skyblue")
                ax.set_ylabel("Rata-rata Jumlah Sewa")
                ax.set_xlabel("Musim")
                st.pyplot(fig)

    with col2:
        st.subheader("Rata-rata Penggunaan per Cuaca")
        if "weathersit" in df_filtered.columns and "cnt" in df_filtered.columns:
            weather_usage = df_filtered.groupby("weathersit")["cnt"].mean()
            if not weather_usage.empty:
                weather_usage.index = weather_usage.index.map(cuaca_map)
                fig, ax = plt.subplots()
                weather_usage.plot(kind="bar", ax=ax, color="lightcoral")
                ax.set_ylabel("Rata-rata Jumlah Sewa")
                ax.set_xlabel("Kondisi Cuaca")
                st.pyplot(fig)

    # --- Pertanyaan 2 ---
    st.header("❓ Pertanyaan 2: Perbedaan Pola Weekday vs Weekend")

    if {"workingday", "hr", "cnt"}.issubset(df_filtered.columns):
        st.subheader("Pola Penggunaan per Jam")
        weekday_data = df_filtered[df_filtered["workingday"] == 1].groupby("hr")["cnt"].mean()
        weekend_data = df_filtered[df_filtered["workingday"] == 0].groupby("hr")["cnt"].mean()

        fig, ax = plt.subplots()
        if not weekday_data.empty:
            ax.plot(weekday_data.index, weekday_data.values, label="Weekday", marker="o")
        if not weekend_data.empty:
            ax.plot(weekend_data.index, weekend_data.values, label="Weekend", marker="s")
        ax.set_xlabel("Jam")
        ax.set_ylabel("Rata-rata Jumlah Sewa")
        ax.legend()
        st.pyplot(fig)

        st.subheader("Rata-rata Penggunaan Weekday vs Weekend")
        day_usage = df_filtered.groupby("workingday")["cnt"].mean()
        if not day_usage.empty:
            day_usage.index = day_usage.index.map(hari_map)
            fig, ax = plt.subplots()
            day_usage.plot(kind="bar", ax=ax, color=["lightgreen", "orange"])
            ax.set_ylabel("Rata-rata Jumlah Sewa")
            st.pyplot(fig)

    # --- Analisis tambahan ---
    st.header("📌 Analisis Tambahan: Heatmap Korelasi")
    numeric_df = df_filtered.select_dtypes(include="number")
    if not numeric_df.empty:
        corr = numeric_df.corr()
        fig, ax = plt.subplots(figsize=(10, 6))
        sns.heatmap(corr, annot=True, cmap="coolwarm", center=0, ax=ax)
        st.pyplot(fig)

    # --- Kesimpulan ---
    st.header("📝 Kesimpulan & Rekomendasi")
    st.markdown("""
    - **Pertanyaan 1:** Musim & cuaca memengaruhi jumlah penyewaan.
    - **Pertanyaan 2:** Weekday menunjukkan pola komuter, weekend lebih rata.

    **Rekomendasi Bisnis:**
    1. Tambah stok sepeda saat musim tinggi & cuaca cerah.
    2. Fokus pemasaran untuk pola weekday vs weekend.
    3. Promosi khusus di periode sepi.
    """)